<a href="https://colab.research.google.com/github/viswanath-s07/FDS-LAB-EXPERIMENTS/blob/main/exp_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

data = {
    "Country": [
        "India", "USA", "Canada", "India", "Australia",
        "Canada", "USA", "India", np.nan, "Australia"
    ],

    "Age": [
        25, 32, 29, 41, 36, 28, np.nan, 45, 39, 34
    ],

    "Salary": [
        35000, 62000, 58000, 72000, np.nan,
        54000, 68000, 81000, 59000, 65000
    ],

    "Purchased": [
        "Yes", "No", "Yes", "Yes", "No",
        "No", "Yes", "No", "Yes", "No"
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")

display(df)

print("Dataset Information:")

df.info()

print("Mode of Country:")

print(df["Country"].mode())

df["Country"] = df["Country"].fillna(
    df["Country"].mode()[0]
)

df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

df["Salary"] = df["Salary"].fillna(
    round(df["Salary"].mean())
)

print("After Data Preprocessing:")

display(df)

Original Dataset:

     Country   Age   Salary Purchased
0      India  25.0  35000.0       Yes
1        USA  32.0  62000.0        No
2     Canada  29.0  58000.0       Yes
3      India  41.0  72000.0       Yes
4  Australia  36.0      NaN        No
5     Canada  28.0  54000.0        No
6        USA   NaN  68000.0       Yes
7      India  45.0  81000.0        No
8        NaN  39.0  59000.0       Yes
9  Australia  34.0  65000.0        No

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    9 non-null      object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes
Mode of Country:
0    India
Name: Country, dtype: object
After Data Preprocessing:

     Country   Age   Salary Purchased
0      India  25.0  35000.0       Yes
1        USA  32.0  62000.0        No
2     Canada  29.0  58000.0       Yes
3      India  41.0  72000.0       Yes
4  Australia  36.0  61556.0        No
5     Canada  28.0  54000.0        No
6        USA  34.0  68000.0       Yes
7      India  45.0  81000.0        No
8      India  39.0  59000.0       Yes
9  Australia  34.0  65000.0        No